
debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080

logging:
  level:
    com.example.demo.Demo1Application: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # ??????? dialect ?? db ? ??. mysql ???? ?????.
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  #entity ? ?? table ???? ???? ???? ddl ?? ????.
#    open-in-view: false
    show-sql: true # sql ?? ????
    properties:
      hibernate.format_sql: true   # ??? ??? debug? ????
      hibernate.hibernate.default_batch_fetch_size: 100 # ?? ????? ??? ? ??? select ??

  h2:
    console:
      enabled: false

  data.rest:
    base-path: /api
    detection-strategy: annotated


#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:

